### ISSUE TITLE
Incorrect MySQL Queries

### ISSUE THREAD

**Issue by ItsEx0tical** [esx-framework/esx-reborn#10]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with esx-reborn and not my personal module / script.

## Expected Result

> The SQL tables should be imported as intended properly and the script should start without errors.

**The queries are invalid for MariaDB 10, they won't import into phpMyAdmin either. Please fix or submit me an SQL file I can import! Thanks.**

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

**An error (and there are more following up but those are just because this procedure is unable to import) is showing up in the console.**

## How to reproduce the problem
Fire up the server with esx-reborn and ghmattimysql.

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

Like I said above, I did not do anything except for properly configuring ghmattimysql & esx-reborn yet my database server is refusing to accept the queries.

## Errors

> Screenshot or direct copy and paste of the error from the console window.

![nlQLHL4 1](https://user-images.githubusercontent.com/73798394/121244031-b14e0380-c89e-11eb-93e7-bee099c4d72c.png)
Here I have used the same database query written in esx-reborn\modules\__core__\db\server\events.lua and fed it into phpMyAdmin and this is what it says:
![phpMyAdmin](https://i.imgur.com/b14fqWL.png)

### Possible Solution

> Fix up the queries for MariaDB 10 (basically what all servers uses).

[Example](https://www.mysqltutorial.org/getting-started-with-mysql-stored-procedures.aspx)

**Comment by ESXCrackhead** [comment]
1) Ensure that you have removed config.json from ghmatti
2) Update MariaDB version, we won't be downgrading SQL queries for older versions of MariaDB

**Comment by ItsEx0tical** [comment]
1. The config.json is removed.
2. I am running the latest stable MariaDB version (MariaDB 10.5.10 database server)

**Comment by ESXCrackhead** [comment]
Do note that in ESX Reborn, all you should have to do is create an empty DB, and it should create the SQL on it's own when you run the server. You should not try to manually import anything.

I just downloaded the latest version of experimental branch, using 10.4.19-MariaDB and it imported everything just fine. I will have to update to MariaDB 10.5.10 in order to test, but I **think** it will work fine and your installation is incorrect. (Not sure why, but I thought MariaDB version was higher than 10, but turns out I was thinking of the subversions not the main version.)

**Comment by ItsEx0tical** [comment]
Sure. Because my DB is empty. The only reason I am trying to parse it manually in phpMyAdmin manually is that it won't import automatically so I was just trying to see what response it gave.

**Comment by ESXCrackhead** [comment]
![image](https://user-images.githubusercontent.com/31637812/121399503-1a279100-c91c-11eb-841b-58ef9146ff30.png)

Works just fine.

**Comment by ESXCrackhead** [comment]
Can't say for certain, as I do not use Linux/Ubuntu, since it's a courtesy port for FiveM, and not recommended.

**Comment by ItsEx0tical** [comment]
Someone had the same issue in #7.

**Comment by ESXCrackhead** [comment]
![image](https://user-images.githubusercontent.com/31637812/121444092-71e1ee80-c954-11eb-9222-49a0daa58ca0.png)

You asked him how he fixed it, but he said how he fixed it right above your comment.

**Comment by Edrow-6** [comment]
**Did you add this line in your server.cfg?** 
`set mysql_connection_string "mysql://user:password@localhost/esx-reborn?charset=utf8mb4&multipleStatements=true"`

**Comment by ItsEx0tical** [comment]
@Edrow-6 Thank you so much! That `?charset=utf8mb4&multipleStatements=true` part fixed it.
