### ISSUE TITLE
Website link in contributions file is dead.

### ISSUE THREAD

**Issue by Fires1** [esx-framework/esx-reborn#11]
https://wiki.esx-framework.org/esx-reborn2/modules/

This site can’t be reached
Check if there is a typo in wiki.esx-framework.org.
If spelling is correct, try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

Pulled from here: https://github.com/esx-framework/esx-reborn/blob/main/CONTRIBUTING.md#esx-v2-and-modules

**Comment by Konijntje-x** [comment]
Fixed in #15 
You can find all the documentiation about it here: https://esx-framework.github.io/es_extended2/modules/ @Fires1

**Comment by ESXCrackhead** [comment]
I'll update this link on the repo in my next update
