### ISSUE TITLE
Failed to load script

### ISSUE THREAD

**Issue by Davinel17** [esx-framework/esx-reborn#13]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x ] I'm using the latest version (develop branch).
- [x ] The issue has occured more than once.
- [x ] I have followed the readme and my setup is correct.
- [x ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x ] I'm certain this is an issue with esx-reborn and not my personal module / script.

## Expected Result

> server start correctly

**_Example text_**

## Current Result

>i install the script correctly , i try mutlitple time install-reinstall.  i have this error below and i cannot join , (infinite loading)
![image](https://user-images.githubusercontent.com/59382061/122656690-e5d97f00-d12a-11eb-990b-35c516d87feb.png)

**_Example Text_**

## How to reproduce the problem

> i juste made a fresh install 

## Errors

> [    c-scripting-core] Creating script environments for esx-reborn
[   script:esx-reborn] Error loading script boot/shared/module.lua in resource esx-reborn: @esx-reborn/boot/shared/module.lua:247: attempt to get length of a nil value (local 'modules')
[   script:esx-reborn] stack traceback:
[   script:esx-reborn] 	@esx-reborn/boot/shared/module.lua:247: in main chunk
[    c-scripting-core] Failed to load script boot/shared/module.lua.
[   script:esx-reborn] Error loading script boot/shared/main.lua in resource esx-reborn: @esx-reborn/boot/shared/main.lua:15: attempt to call a nil value (field 'Boot')
[   script:esx-reborn] stack traceback:
[   script:esx-reborn] 	@esx-reborn/boot/shared/main.lua:15: in main chunk
[    c-scripting-core] Failed to load script boot/shared/main.lua.
[ citizen-server-impl] Started resource esx-reborn

**Comment by ESXCrackhead** [comment]
please try experimental branch, and update your issue here

**Comment by Konijntje-x** [comment]
_Sidenote:_ 
I used esx-reborn experimental, newest version and followed the installation guides and i don't have errors.
First i had this to, i installed esx-reborn experimental newest version, used ghmattimysql new update, deleted config from ghmattimysql.
Make sure this is right: `set mysql_connection_string "mysql://username:password@localhost/esx-reborn?charset=utf8mb4&multipleStatements=true"`

**Comment by Konijntje-x** [comment]
@Davinel17

**Comment by Konijntje-x** [comment]
-- Update: i have this error with the main branch.
Update to experimental.
