### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by eevee911** [esx-framework/esx-reborn#28]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ ] I'm using the latest version (develop branch).
- [ x] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [ x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ x] I'm certain this is an issue with esx-reborn and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

There is a typo in a function so I suggest you fix it

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

There is a typo in a function so I suggest you fix it. it cannot find the function.

![image](https://user-images.githubusercontent.com/24459911/126124988-faac64d2-679b-48ee-865d-ce5a99e06347.png)

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?
1. I just watched the code.

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`getAccoutns() == nil`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

https://github.com/esx-framework/esx-reborn/blob/265331b6365de86845c7ffa9b01954dd12dd05d8/modules/__core__/account/server/main.lua#L65

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

` local accounts = identity:getAccounts()`

**Comment by Konijntje-x** [comment]
Hey
Thanks for reporting the bug, so even beginners can easily get started!
It's now fixed in #29 

Kind regards
> Konijntje-x
> ESX Support

**Comment by ESXCrackhead** [comment]
Will be pushed shortly.
