### ISSUE TITLE
Error loading script when starting the server

### ISSUE THREAD

**Issue by Edrow-6** [esx-framework/esx-reborn#6]
## Issue Checklist

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with esx-reborn and not my personal module / script.

## Expected Result

**_Running Smooth without errors_**

## Current Result

![image](https://user-images.githubusercontent.com/25459251/119733891-73061c80-be7a-11eb-8a9f-b8915e21d33c.png)

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. **_Install esx-reborn_**

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`[    c-scripting-core] Creating script environments for esx-reborn
[   script:esx-reborn] Error loading script boot/shared/module.lua in resource esx-reborn: @esx-reborn/boot/shared/module.lua:247: attempt to get length of a nil value (local 'modules')
[   script:esx-reborn] stack traceback:
[   script:esx-reborn]  @esx-reborn/boot/shared/module.lua:247: in main chunk
[    c-scripting-core] Failed to load script boot/shared/module.lua.
[   script:esx-reborn] Error loading script boot/shared/main.lua in resource esx-reborn: @esx-reborn/boot/shared/main.lua:15: attempt to call a nil value (field 'Boot')
[   script:esx-reborn] stack traceback:
[   script:esx-reborn]  @esx-reborn/boot/shared/main.lua:15: in main chunk
[    c-scripting-core] Failed to load script boot/shared/main.lua.
[ citizen-server-impl] Started resource esx-reborn`

### Possible Solution
IDK

**Comment by Jhosan7** [comment]
From the readme: WARNING: The file may not already exists if it's your first installation, just create a file named modules.json in the esx-reborn/modules/__user__/ directory. Create that file with [] inside and try

**Comment by Edrow-6** [comment]
Hi, I'm sorry I thought I did. Now I have a new error concerning the database :/

Log: https://hastebin.com/ikaderikoh.sql
