### ISSUE TITLE
MariaDB Push table & Syntax error

### ISSUE THREAD

**Issue by Edrow-6** [esx-framework/esx-reborn#7]
## Bug Report

Now I have a new error concerning the database :(
However I have created the database and the accesses are correct.

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with esx-reborn and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

**_No errors_**

## Current Result

![image](https://user-images.githubusercontent.com/25459251/119843560-f4f05700-bf07-11eb-9387-6d7d49099d93.png)
![image](https://user-images.githubusercontent.com/25459251/119843595-fe79bf00-bf07-11eb-96ba-df4e899541e1.png)
![image](https://user-images.githubusercontent.com/25459251/119843645-08032700-bf08-11eb-8e8b-bfbfe2889e1a.png)
![image](https://user-images.githubusercontent.com/25459251/119843687-12bdbc00-bf08-11eb-86ad-dfbe68dc41b1.png)

**_Syntax error in mariadb request_**

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. **_Starting the server normally_**

## Errors

End of error log (same on screens): https://hastebin.com/ikaderikoh.sql

### Possible Solution

`It's a client error or esx related? Idk how to solve this`

**Comment by Edrow-6** [comment]
Ok it's patched, config.cfg in ghmattimysql break all.

**Comment by ItsEx0tical** [comment]
How did you fix this? I still have this same issue on the latest version of esx-reborn (the experimental branch).
